Repository redis-developer/redis-ai-resources, pull requests merged in 2025-05, with the labels that each got.

#80 Add embeddings cache to recipes
  python-recipes/RAG/01_redisvl.ipynb
  python-recipes/RAG/04_advanced_redisvl.ipynb
  python-recipes/vector-search/01_redisvl.ipynb
  python-recipes/vector-search/02_hybrid_search.ipynb
Labels: documentation

#77 fixing path in README.md
  java-recipes/README.md
Labels: bug

#85 Add recipe for LiteLLM + Redis
  .github/ignore-notebooks.txt
  .gitignore
  README.md
  python-recipes/gateway/00_litellm_proxy_redis.ipynb
Labels: enhancement

#90 Add recipe for transaction search and feature examples
  README.md
  python-recipes/feature-store/00_feast_credit_score.ipynb
  python-recipes/feature-store/01_card_transaction_search.ipynb
  python-recipes/feature-store/resources/transactions_200.json
Labels: enhancement
